### ISSUE TITLE
[FR] List all tables command

### ISSUE THREAD

**Issue by emisjerry** [hymkor/sqlbless#2]
Could you add a command to list all tables in the database? 
For example, we can use ".tables" in sqlite3.exe to list all the tables.

For now, i use the following SQL statements to list tables:

- SQL Server: select name from sysobjects where xtype='U';
- SQlite3: SELECT name FROM sqlite_master WHERE type='table';

It would be nice if the command to display the column structure was also available. Such as Oracle's "describe" command.

**Comment by hymkor** [comment]
`DESC` or `\d` command is available for listing them.

- `DESC` or `\d` without aguments shows the list of tables.
- `DESC tablename` or `\d tablename` shows the specification of the table.

![image](https://github.com/hymkor/sqlbless/assets/3752189/d8e75830-4055-4332-a345-30db5f730460)

Since I am used to Oracle, the specifications are similar to Oracle's SQL\*Plus. If you have any suggestions for improvement about `DESC` command, Would you post them in this issue ?

**Comment by emisjerry** [comment]
Thanks for your reply. 

Is there any 'secret' command other than ‘desc’, which is not mentioned in the README?
How about the ".tables" command?

**Comment by hymkor** [comment]
I thought I had written it, but I didn't. (I wasn't trying to hide it, **I just forgot**)

Thank you for pointing that out. I would confirm and update README.

Is `DESC ;` **without arguments** equivalent to `.tables` ?

**Comment by emisjerry** [comment]
`DESC ;` works.
